# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  workflow_dispatch

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./TestTypegenNpm

    steps:
      - name: Checkout 
        uses: actions/checkout@v3
        
      - name: Nodejs16 setup
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Setup nuget
        uses: nuget/setup-nuget@v1.0.5

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x

      - name: Install TypeGen Globally
        run: dotnet tool install --global dotnet-typegen --version 4.0.1
      
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Generate Typescript files
        run: dotnet-typegen generate
          
      - name: Run CI
        run: npm ci
      
      # - name: NPM Publish
      #   run: npm publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{secrets.npm_token}}
